{% set name = "pydocket" %}
{% set version = "0.15.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3cf7030941f175f073cf05fc6fdf0ceede0af640f786de7dd22556d08025799f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - docket = docket.__main__:app

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python
    - cachetools >=5.0.0
    - cloudpickle >=3.1.1
    - exceptiongroup >=1.2.0
    - fakeredis >=2.32.1
    - lupa >=2.0  # [py<313]
    - opentelemetry-api >=1.30.0
    - opentelemetry-exporter-prometheus >=0.51b0
    - prometheus_client >=0.21.1
    - py-key-value-aio >=0.3.0
    - python-json-logger >=2.0.7
    - redis-py >=5
    - rich >=13.9.4
    - typer >=0.15.1
    - typing-extensions >=4.12.0

test:
  imports:
    - docket

about:
  home: https://github.com/chrisguidry/docket
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A distributed background task system for Python functions
  description: |
    Docket is a distributed background task system for Python functions with a
    focus on scheduling future work. It requires a Redis server with Streams
    support (Redis 5.0.0+).
  dev_url: https://github.com/chrisguidry/docket
  doc_url: https://github.com/chrisguidry/docket

extra:
  recipe-maintainers:
    - chrisguidry
    - zzstoatzz
